### PR TITLE
Fix incompatibility with latest version IDEA

### LINKED ISSUE #10: Support 2020.2
Currently doesn't work with 2020.2 - intellij reports the plugin as incompatible and won't list it for installation again after removing the current version.

### PR DESCRIPTION
**Pull request by PeiqingMa**
Add setting `updateSinceUntilBuild false`.
Can work in IDEA 2020.2 (fix #10 )

### CODE REVIEW

**Comment by tomas-milata** [comment]
Thanks a lot for trying to fix this!

I'm not convinced this is the right way though. Presumably the `updateSinceUntilBuild` will just remove the since and until values from the generated `plugin.xml`, which means the plugin will pretend compatibility with all versions but might fail at runtime?

**Comment by tomas-milata** [comment]
I've released a 2020.2-compatible version now. See the details in https://github.com/tomas-milata/intelliroutes/issues/10.

**Comment by PeiqingMa** [comment]
I understand your concern. Most of the plugins I'm using works fine without update after IDEA upgraded. It's really annoying this plugin can't work every time IDEA has a new version.

**Comment by tomas-milata** [comment]
Yes, that's fair. Point taken.

**Pull request closed without merging**
